"""empty message

Revision ID: 7600250f9897
Revises: bc23f2cac65c
Create Date: 2021-01-27 18:37:38.301384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7600250f9897'
down_revision = 'bc23f2cac65c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todo', 'list_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todo', 'list_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
